apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: rss-radar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: ghcr.io/eliasmorio/rss-radar-rewrite/worker:${version}
        env:
          - name: DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                key: url
                name: rss-radar-postgres
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rss-radar-postgres
                key: password
