services:
  db_rss-radar:
    image: postgres:16-alpine
    container_name: db_rss-radar
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data_rss-radar:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./definitions.json:/opt/definitions.json
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

volumes:
  db_data_rss-radar: