apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: rss-radar-explore-queue
spec:
  name: rss-radar.explore.queue
  rabbitmqClusterReference:
    name: rabbitmq-cluster
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: rss-radar-crawl-queue
spec:
  name: rss-radar.crawl.queue
  rabbitmqClusterReference:
    name: rabbitmq-cluster
