apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - name: web-api
          image: {{ .Values.image.webApi | quote }}
          ports:
            - containerPort: 80
          env:
            - name: DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: {{ .Values.references.postgresConfigMap }}
            - name: DATASOURCE_DATABASE
              value: {{ .Values.config.datasource.database | quote }}
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: {{ .Values.references.rabbitmqConfigMap }}
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
                  name: {{ .Values.references.appConfigMap }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.config.otel.webApiServiceName | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
