apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rss-radar.fullname" . }}-web-api
  labels:
    {{- include "rss-radar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rss-radar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web-api
  template:
    metadata:
      labels:
        {{- include "rss-radar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web-api
    spec:
      containers:
        - name: web-api
          image: {{ .Values.image.webApi | quote }}
          ports:
            - containerPort: 80
          env:
            - name: DATASOURCE_HOST
              value: postgres-cluster
            - name: DATASOURCE_DATABASE
              value: rss-radar
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: password
            - name: RABBITMQ_HOST
              value: rabbitmq-cluster
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.observability.svc.cluster.local:4318
            - name: OTEL_SERVICE_NAME
              value: rss-radar-web-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rss-radar.fullname" . }}-web-api
  labels:
    {{- include "rss-radar.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rss-radar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}
