apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rss-radar.fullname" . }}-worker
  labels:
    {{- include "rss-radar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rss-radar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "rss-radar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.image.worker | quote }}
          env:
            - name: DATASOURCE_URL
              value: jdbc:postgresql://postgres-cluster:5432/rss-radar
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: password
            - name: RABBITMQ_HOST
              value: rabbitmq-cluster
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.observability.svc.cluster.local:4318
            - name: OTEL_SERVICE_NAME
              value: rss-radar-worker
          resources:
            requests:
              memory: {{ .Values.resources.worker.requests.memory | quote }}
              cpu: {{ .Values.resources.worker.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.worker.limits.memory | quote }}
              cpu: {{ .Values.resources.worker.limits.cpu | quote }}
