apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rss-radar.fullname" . }}-worker
  labels:
    {{- include "rss-radar.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rss-radar.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "rss-radar.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.image.worker | quote }}
          env:
            - name: DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: {{ .Values.references.postgresConfigMap }}
            - name: DATASOURCE_DATABASE
              value: {{ .Values.config.datasource.database | quote }}
            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.postgresSecret }}
                  key: password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: {{ .Values.references.rabbitmqConfigMap }}
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.references.rabbitmqSecret }}
                  key: password
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
                  name: {{ .Values.references.appConfigMap }}
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: {{ .Values.references.appConfigMap }}
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.references.appConfigMap }}
                  key: OTEL_SERVICE_NAME
          resources:
            requests:
              memory: {{ .Values.resources.worker.requests.memory | quote }}
              cpu: {{ .Values.resources.worker.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.worker.limits.memory | quote }}
              cpu: {{ .Values.resources.worker.limits.cpu | quote }}
