# Import common configuration
spring:
  config:
    import: classpath:application-common.yml
  application:
    name: rss-radar-web-api

# Service-specific configuration
cross:
  origin:
    url: "*"
