spring:
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/rss_radar
    username: rss-radar
    password: rss-radar