spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rss_radar
    username: rss-radar
    password: rss-radar
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# Pagination configuration for local development
batch:
  page:
    size: 50
logging:
  level:
    fr.emorio: DEBUG
