spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: rss-radar
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
  rabbitmq:
    host: "rabbitmq"
    port: 5672
    username: "guest"
    password: "guest"
  
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.xml
    enabled: true

banned:
  urls: "https://dwh.lequipe.fr/api/edito/rss?path=/**"