spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.xml
    enabled: true

banned:
  urls: "https://dwh.lequipe.fr/api/edito/rss?path=/**"

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
  level:
    fr.emorio: DEBUG

otel:
  propagators:
    - tracecontext
    - b3
  resource:
    attributes:
      deployment.environment: production
      service:
        name: worker
        namespace: rss-radar