spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: rss-radar
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "admin"
    password: "secret"
  
  liquibase:
    change-log: classpath*:db/changelog/db.changelog-master.xml