# Import common configuration
spring:
  config:
    import: classpath:application-common.yml
  application:
    name: rss-radar-worker

# Service-specific configuration
banned:
  urls: "https://dwh.lequipe.fr/api/edito/rss?path=/**"

rabbitmq:
  explore.queue.name: rss-radar.explore.queue
