apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - name: web-api
          image: ghcr.io/eliasmorio/rss-radar-rewrite/web-api:latest
          ports:
            - containerPort: 80
          env:
            # DATABASE
            - name: DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: postgres-config

            - name: DATASOURCE_DATABASE
              value: rss-radar

            - name: DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rss-radar.postgres-cluster.credentials.postgresql.acid.zalan.do
                  key: username
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rss-radar.postgres-cluster.credentials.postgresql.acid.zalan.do
                  key: password

            # RABBITMQ
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  key: RABBITMQ_HOST
                  name: rabbitmq-config
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: password

            # OTEL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
                  name: app-config
            - name: OTEL_SERVICE_NAME
              value: web-api
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
