name: build docker

on:
  push:
    branches:
      - develop-ci

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build application
        run: mvn clean package --projects :web-api --also-make --batch-mode

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build . --build-arg JAR_FILE=services/web-api/target/app.jar -t ${{ github.sha }}

      - name: Push Docker image
        run: |
          docker tag ${{ github.sha }} ghcr.io/${{ github.repository }}/web-api:latest
          docker push ghcr.io/${{ github.repository }}/web-api:latest