name: Frontend

on:
  push:
    branches: [main]
    paths:
      - services/frontend/**
      - .github/workflows/frontend.yml
  
  
jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: frontend