name: Web API

on:
  push:
    branches: [main]
    paths:
      - services/web-api/**
      - libs/common/**
      - .github/workflows/web-api.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: web-api