name: Web API

on:
  release:
    types: [published]
    branches: [main]

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: web-api
      tag: ${{ github.event.release.tag_name }}
