name: Worker

on:
  push:
    branches: [main, develop-ci]
    paths:
      - services/worker/**
      - libs/common/**
      - .github/workflows/worker.yml 
  pull_request:
    branches: [main, develop]


jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: worker