name: Worker

on:
  push:
    branches: [develop]
    paths:
      - services/worker/**
      - libs/common/**
      - .github/workflows/worker.yml
  release:
    branches: [main]
    paths:
      - services/worker/**
      - libs/common/**
      - .github/workflows/worker.yml


jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: worker